# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-16 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170813_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuserprofile',
            name='address',
            field=models.CharField(default='', max_length=128),
        ),
    ]
