# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-17 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_tuserprofile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuserprofile',
            name='subscr',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tuserprofile',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
