# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-18 20:46
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_remove_tpost_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tpost',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tpost',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
