# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-18 20:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170618_2047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tpost',
            old_name='user_id',
            new_name='user',
        ),
    ]
