# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-10 19:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20170706_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='tlike',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
